%%% setup training parameters %%%
l1 = default_layer('fliplr', true, 'Nw', 10, 'num_filters', 24, 'phi_sparsity', 0.003,...
    'phi_sparsity_lambda', 5, 'Npooling', 2, 'learningRate', 0.02, 'l2reg', 0.01, ...
    'batch_size', 10,'batch_Nw', 50, 'num_trials',200,...
    'id',1, 'initial_momentum', 0.5, 'final_momentum', 0.9,'momentum_change_points', 5,...
    'K_CD',1, 'sigma_start',0.2, 'std_gaussian', 0.2, 'sigma_stop', 0.1,'database','face');

l2 = default_layer( 'Nw', 10, 'num_filters', 40, 'phi_sparsity', 0.005,...
    'phi_sparsity_lambda', 5, 'Npooling', 2, 'learningRate', 0.005, ...
    'batch_size', 2, 'batch_Nw', 28, 'num_trials',200,...
    'id',2, 'database','');

l3 = default_layer( 'Nw', 7, 'num_filters', 24, 'phi_sparsity', 0.005,...
    'phi_sparsity_lambda', 10, 'Npooling', 2, 'learningRate', 0.00005, 'l2reg', 0.05, ...
    'batch_size', 2, 'batch_Nw', 8, 'num_trials',300,...
    'id',3, 'K_CD',1, 'sigma_start',1, 'std_gaussian', 1, 'sigma_stop', 0.1);

layers = {l1, l2, l3};
%%%%%%%%%%%%%%%%%%%%%%


%%% train and test %%%
for i=1:numel(layers)
   layers = trainCDBN(layers, i);
   layers = crbm_forward(layers, i);
   save_layer_figure(layers, i);
end
%%%%%%%%%%%%%%%%%%%%%%

save_env(layers, mfilename);
